In this exercise, we will learn:
    
    1. How to load data
    2. How to find some attributes of the data
    3. How to create sliding windows

In [2]:
pip list

Package                   Version
------------------------- ---------
anaconda-anon-usage       0.4.4
anaconda-client           1.12.3
anaconda-cloud-auth       0.5.1
anaconda-navigator        2.6.0
annotated-types           0.6.0
archspec                  0.2.3
asttokens                 3.0.0
attrs                     23.1.0
bleach                    6.1.0
boltons                   23.0.0
Brotli                    1.0.9
certifi                   2025.1.31
cffi                      1.16.0
chardet                   4.0.0
charset-normalizer        2.0.4
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
conda                     25.1.1
conda-content-trust       0.2.0
conda-libmamba-solver     24.1.0
conda-package-handling    2.2.0
conda_package_streaming   0.9.0
conda-repo-cli            1.0.88
conda-token               0.4.0
contourpy                 1.3.1
cryptography              42.0.5
cycler                    0.12.1
debugpy              

In [20]:
# 1. Variables and Data Types
x = 10  # Integer
y = 3.14  # Float
name = "Mattia De Munari"  # String
is_active = True  # Boolean
fruits = ["apple", "banana", "cherry"]  # List
person = {"name": "Yao", "age": 25}  # Dictionary
numbers = (1, 2, 3)  # Tuple
unique_values = {1, 2, 3, 3}  # Set

print(f"x: {x}, y: {y}, name: {name}, is_active: {is_active}")
print(f"Fruits: {fruits}, Person: {person}, Numbers: {numbers}, Unique Values: {unique_values}")

x: 10, y: 3.14, name: Mattia De Munari, is_active: True
Fruits: ['apple', 'banana', 'cherry'], Person: {'name': 'Yao', 'age': 25}, Numbers: (1, 2, 3), Unique Values: {1, 2, 3}


In [14]:
# 2. Conditional Statements
if x > 5:
    print("x is greater than 5")
elif x == 5:
    print("x is 5")
else:
    print("x is less than 5")

x is greater than 5


In [15]:
x = 7

if x > 5 and x < 10:
    print("5<x<10")
else:
    print("x<=5 or x>=10")



5<x<10


In [16]:
x = 7

if x >= 10 or x <= 5:
    print("x<=5 or x>=10")
else:
    print("5<x<10")

5<x<10


In [17]:
print("For Loop:")
for fruit in fruits:
    print(fruit)

print("While Loop:")
counter = 0
while counter < 3:
    print(f"Counter: {counter}")
    counter += 1

For Loop:
apple
banana
cherry
While Loop:
Counter: 0
Counter: 1
Counter: 2


In [19]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Mattia"))

Hello, Mattia!


In [24]:
try:
    results = [1,2,3,4,5,'fruit',6,7]  # A list contain int and string
    for result in results:
        print(result+1)
except TypeError:
    print("Error: unsupport value type error not allowed.")
finally:
    print("This always executes.")

2
3
4
5
6
Error: unsupport value type error not allowed.
This always executes.


In [25]:

results = [1,2,3,4,5,'fruit',6,7]
 
for result in results:
    try:
        result = int(result)
        print(result)
    except ValueError:
        print(f"Error converting {result} to int")
    except Exception as e:
        print(f"An error occurred: {e}")

1
2
3
4
5
Error converting fruit to int
6
7


In [29]:
import math
print("Square root of 16:", math.sqrt(16))

Square root of 16: 4.0


In [30]:
f = open("./txt_exercise1/demofile.txt", "r")
print(f.read())

f = open("./txt_exercise1/demofile2.txt", "w")
f.write("Now the file has more content!")
f.close()

Hello! Welcome to demofile.txt
This file is for testing purposes.
Good Luck!


In [31]:
f = open("./txt_exercise1/demofile2.txt", "a")
f.write("Now the file has more content!\n")
f.close()

In [32]:
# Loading libraries
# Numpy is utilized to manipulate data containers
import numpy as np 

In [33]:
# Loading the data recorded for the class "walking"
# This loads the data into a NumPy array for further processing or analysis in Python
# The data is loaded into a "matrix" structure with two dimensions
data = np.loadtxt("./walking.csv", delimiter=",")

In [38]:
# Here we access the number of components in the first dimension (number of samples)
num_samples = data.shape[0]
print(f"Number of samples: {num_samples}")

# Here we access the number of components in the first dimension (number of sensor channels)
num_channels = data.shape[1]
print(f"Number of sensor channels: {num_channels} corresponding to ACC X, Y, Z and GYRO X, Y, Z")

Number of samples: 61266
Number of sensor channels: 6 corresponding to ACC X, Y, Z and GYRO X, Y, Z


In [39]:
# Let's have a look at the data
print("     ACC X,       ACC Y,     ACC Z,     GYRO X,     GYRO Y,     GYRO Z")
print(data)

     ACC X,       ACC Y,     ACC Z,     GYRO X,     GYRO Y,     GYRO Z
[[ 6.3906e-02 -6.5013e-02 -1.1267e-01  4.1905e-03  2.7495e-02 -8.9308e-03]
 [ 1.5697e-02  7.7307e-04 -1.1857e-01 -3.7507e-03  3.0604e-03 -8.9308e-03]
 [-1.5182e-03  5.3167e-05 -8.9513e-02 -2.4520e-02 -5.4917e-03  7.5625e-03]
 ...
 [-2.9038e+00  1.7022e+00 -5.0675e-01 -7.1477e-01 -3.5953e-03 -3.5306e-01]
 [ 7.2340e-01 -1.1946e+00  2.9736e-01 -6.5512e-01 -7.7911e-01 -4.1485e-01]
 [ 3.6843e+00 -2.3661e+00  1.7814e-01 -2.0558e-01 -2.2197e-01 -2.1458e+00]]
